VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clsŒ‹‰Ê"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Dim lŒ‹‰Ê“ú As Date
Dim lŒ‹‰Ê As String

Public Property Let Œ‹‰Ê“ú(value As Date)
    lŒ‹‰Ê“ú = value
End Property
Public Property Get Œ‹‰Ê“ú() As Date
    Œ‹‰Ê“ú = lŒ‹‰Ê“ú
End Property

Public Property Let Œ‹‰Ê(value As String)
    lŒ‹‰Ê = value
End Property
Public Property Get Œ‹‰Ê() As String
    Œ‹‰Ê = lŒ‹‰Ê
End Property

